package com.pictureperfectx.app.filter

import android.content.Context
import android.util.Log
import androidx.compose.ui.graphics.Color
import org.json.JSONObject

/**
 * Loads the LUT pack described by `assets/luts/manifest.json` and exposes it as [Filter]s.
 *
 * The list always starts with [original] (an unfiltered passthrough) followed by the 100 packaged
 * looks. Parsing happens once and is cached; the manifest is generated by `tools/generate_luts.py`.
 */
object FilterCatalog {

    private const val TAG = "FilterCatalog"
    private const val MANIFEST = "luts/manifest.json"

    val original = Filter(
        id = Filter.ORIGINAL_ID,
        displayName = "Original",
        category = "original",
        lutAsset = null,
        swatchStart = Color(0xFF3A3A3D),
        swatchEnd = Color(0xFF161618),
    )

    @Volatile
    private var cached: List<Filter>? = null

    /** Full selectable list: Original first, then the packaged LUTs. Cached after first load. */
    fun load(context: Context): List<Filter> {
        cached?.let { return it }
        return synchronized(this) {
            cached ?: buildList {
                add(original)
                addAll(parseManifest(context))
            }.also { cached = it }
        }
    }

    fun byId(context: Context, id: String): Filter =
        load(context).firstOrNull { it.id == id } ?: original

    private fun parseManifest(context: Context): List<Filter> = try {
        val json = context.assets.open(MANIFEST).bufferedReader().use { it.readText() }
        val luts = JSONObject(json).getJSONArray("luts")
        (0 until luts.length()).map { i ->
            val o = luts.getJSONObject(i)
            Filter(
                id = o.getString("id"),
                displayName = o.getString("name"),
                category = o.optString("category", "creative"),
                lutAsset = o.getString("asset"),
                swatchStart = parseColor(o.getString("swatchStart")),
                swatchEnd = parseColor(o.getString("swatchEnd")),
            )
        }
    } catch (e: Exception) {
        Log.e(TAG, "Failed to load LUT manifest; only Original will be available", e)
        emptyList()
    }

    private fun parseColor(hex: String): Color =
        Color(hex.removePrefix("#").toLong(16) or 0xFF000000L)
}
