package com.pictureperfectx.app.filter

import androidx.compose.ui.graphics.Color

/**
 * One selectable look. Every look except [FilterCatalog.original] is backed by a real 512x512
 * GPUImage lookup table shipped in `assets/luts/` and described by `assets/luts/manifest.json`
 * (generated by `tools/generate_luts.py`).
 *
 * @param id          Stable id persisted alongside captured photos.
 * @param displayName Shown under the thumbnail.
 * @param category    "camera" | "lens" | "film" | "creative" | "original" (drives the section chips).
 * @param lutAsset    Path under `assets/` to the LUT PNG, or null for the passthrough Original.
 * @param swatchStart / swatchEnd  Chip gradient colors (the look applied to a light / dark tone).
 */
data class Filter(
    val id: String,
    val displayName: String,
    val category: String,
    val lutAsset: String?,
    val swatchStart: Color,
    val swatchEnd: Color,
) {
    val isOriginal: Boolean get() = lutAsset == null

    companion object {
        const val ORIGINAL_ID = "original"
    }
}
