package com.pictureperfectx.app.filter

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Validates the packaged LUT pack (generated by tools/generate_luts.py) and the Filter model.
 * Reads the assets directly so it needs no Android runtime.
 */
class FilterCatalogTest {

    private val lutDir: File by lazy {
        listOf(
            File("src/main/assets/luts"),
            File("app/src/main/assets/luts"),
            File("android/app/src/main/assets/luts"),
        ).firstOrNull { it.isDirectory } ?: error("luts asset dir not found from ${File(".").absolutePath}")
    }

    private val manifest: String by lazy { File(lutDir, "manifest.json").readText() }

    @Test
    fun pack_hasExactly100Luts() {
        val pngCount = lutDir.listFiles { f -> f.extension == "png" }?.size ?: 0
        assertEquals(100, pngCount)
        assertEquals(100, Regex("\"id\":").findAll(manifest).count())
    }

    @Test
    fun pack_hasAtLeastHalfCameraOrLens() {
        val cameras = Regex("\"category\": ?\"camera\"").findAll(manifest).count()
        val lenses = Regex("\"category\": ?\"lens\"").findAll(manifest).count()
        assertTrue("expected >=50 camera/lens, got ${cameras + lenses}", cameras + lenses >= 50)
    }

    @Test
    fun everyManifestAssetFileExists() {
        Regex("\"asset\": ?\"luts/([^\"]+)\"").findAll(manifest).forEach { m ->
            val name = m.groupValues[1]
            assertTrue("missing LUT file $name", File(lutDir, name).exists())
        }
    }

    @Test
    fun original_isPassthrough() {
        assertEquals(Filter.ORIGINAL_ID, FilterCatalog.original.id)
        assertTrue(FilterCatalog.original.isOriginal)
    }

    @Test
    fun filter_withLut_isNotOriginal() {
        val f = Filter("x", "X", "film", "luts/x.png", FilterCatalog.original.swatchStart, FilterCatalog.original.swatchEnd)
        assertFalse(f.isOriginal)
    }
}
